spring:
  application:
    name: turning-point-api
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:turning_point}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

wx:
  miniapp:
    appid: ${WX_APPID:your_appid}
    secret: ${WX_SECRET:your_secret}

coze:
  api:
    key: ${COZE_API_KEY:your_coze_key}
    project-id: ${COZE_PROJECT_ID:7600759893704048649}
    base-url: https://jcp33s7bqh.coze.site/stream_run
