spring:
  application:
    name: turning-point-api
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:turning_point}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

wx:
  miniapp:
    appid: ${WX_APPID:your_appid}
    secret: ${WX_SECRET:your_secret}

coze:
  api:
    token: ${COZE_TOKEN:eyJhbGciOiJSUzI1NiIsImtpZCI6ImNhMmQ5ZWNiLTcwYTMtNDNhYS1hYjhkLTJkYWM3MWMzNDIyYSJ9.eyJpc3MiOiJodHRwczovL2FwaS5jb3plLmNuIiwiYXVkIjpbImMzRnhzVEd0VW80WDFwR0x4OVJkRmQ3bmg3TU1sYnBHIl0sImV4cCI6ODIxMDI2Njg3Njc5OSwiaWF0IjoxNzY5NjkyOTEwLCJzdWIiOiJzcGlmZmU6Ly9hcGkuY296ZS5jbi93b3JrbG9hZF9pZGVudGl0eS9pZDo3NjAwNzY5NzQ5OTkxMDMwODEwIiwic3JjIjoiaW5ib3VuZF9hdXRoX2FjY2Vzc190b2tlbl9pZDo3NjAwNzczMTc1ODYwNzg5MjQ4In0.omkF_PwGEUHzt8SRKt7CZVbaINyFfZfQVE4AtqOeX1E6UYWdGOrsiT4sRE1FlnjysrfwOMJiR7wqMzy3L4LXZjbpc7oa1hcA0wDUvQKO1w3AkIXHevu5z-MuH6UMLpWEkwhYZpcp766rxWJbQwrqVe_FQlaTzGpQmr48LhRefxVZYGoPKyLAYInY3aqd9NIWyHSAJYowFolERx56GdSNCKL8bUykAsigXOKD6kfLjeVfrGyHp3z8-Ry4EsLLRCq9xpgwCys7co92nWf0rp_JQKshwygsBcJhfyq8uoxbvo8jWKlYVBWJYDNafHrr02DQu0Yyn3Uvse0zt_IBtYkSKQ}
    project-id: ${COZE_PROJECT_ID:7600759893704048649}
    session-id: ${COZE_SESSION_ID:iigSbU_Nb52jD6bz7DZ4y}
    base-url: ${COZE_BASE_URL:https://jcp33s7bqh.coze.site/stream_run}
